# Include syntax requires Docker compose > 2.20.3
# https://docs.docker.com/compose/release-notes/#2203
include:
  # Creates a standard Postgres instance
  - path: services/postgres.yaml
  # Creates the internal MongoDB replica set
  - path: services/mongo.yaml
  # Demo Django backend server and front-end web client
  - path: ps-django-backend.yaml
  #- path: ps-nodejs-demo.yaml
services:
  # Extend PowerSync with Mongo and Postgres healthchecks
  powersync:
    extends:
      file: services/powersync.yaml
      service: powersync
    depends_on:
      mongo-rs-init:
        condition: service_completed_successfully
      pg-db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pg-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  # Postgres data
  pg_data:
  # pgAdmin data
  pgadmin_data:
