# See Documentation for more information:
# https://docs.powersync.com/usage/sync-rules
# Note that changes to this file are not watched.
# The service needs to be restarted for changes to take effect.
bucket_definitions:
  global:
    data:
      - SELECT * FROM lists

  todos:
    parameters:
      - SELECT id AS todo_id
        FROM todos
        WHERE list_id IN request.jwt() ->> 'list_id'
    data:
      - SELECT * FROM todos WHERE id = bucket.todo_id
